# -*- coding: utf-8 -*-
# Grammaire N4 et N3 : fiches de référence (structure, emploi, exemple, traduction). Pas de quiz pour l'instant.
from content import T, P, N, H

def g(rows):
    return T(['Structure', 'Emploi', 'Exemple', 'Traduction'], rows, jp=(0, 2), ro=())

def sub(title, intro, rows, note=None):
    bl = [P(intro), g(rows)]
    if note: bl.append(N(note))
    return {'title': title, 'blocks': bl}

# ═════════════════════════ N4 ═════════════════════════
N4 = [
 sub('局面 — Action en cours, résultat, préparation',
  'Ces structures disent à quel stade se trouve une action : sur le point de commencer, en cours, finie, faite à l’avance ou regrettée.',
  [
   ['V-てある', 'État résultant d’une action faite volontairement par quelqu’un (verbe transitif, objet avec が)', '窓が開けてあります。', 'La fenêtre a été ouverte (et elle l’est toujours).'],
   ['V-ておく', 'Faire à l’avance, en préparation ; ou laisser en l’état', '旅行の前に、ホテルを予約しておきます。', 'Je réserve l’hôtel avant le voyage.'],
   ['V-てしまう', 'Action achevée ; ou regret, action involontaire', '財布を忘れてしまいました。', 'J’ai oublié mon portefeuille (zut).'],
   ['V-てみる', 'Essayer de faire, tenter l’expérience', 'この料理を食べてみてください。', 'Goûtez ce plat.'],
   ['V-るところだ', 'Sur le point de…', '今、出かけるところです。', 'Je suis sur le point de sortir.'],
   ['V-ているところだ', 'En train de… (en plein déroulement)', '今、料理しているところです。', 'Je suis justement en train de cuisiner.'],
   ['V-たところだ', 'Vient juste de… (à l’instant)', 'たった今、着いたところです。', 'Je viens d’arriver à l’instant.'],
   ['V-たばかりだ', 'Vient de… (sentiment de « récent », période plus large)', '先月、日本に来たばかりです。', 'Je ne suis arrivé au Japon que le mois dernier.'],
   ['V-はじめる', 'Commencer à (radical en ます + はじめる)', '雨が降りはじめました。', 'Il s’est mis à pleuvoir.'],
   ['V-つづける', 'Continuer à, ne pas arrêter de', '三時間も歩きつづけました。', 'J’ai marché sans m’arrêter pendant trois heures.'],
   ['V-おわる', 'Finir de', 'もうご飯を食べおわりました。', 'J’ai déjà fini de manger.'],
   ['V-すぎる', 'Trop… (radical en ます, adjectif sans い / な)', '昨日は食べすぎました。', 'Hier j’ai trop mangé.'],
  ],
  'てある décrit le résultat d’une action voulue (objet + が : 窓が開けてある), alors que ている avec un verbe intransitif décrit un état (窓が開いている). ところ = moment précis ; ばかり = « récent » au sens large.'),

 sub('許可・禁止・義務 — Permission, interdiction, devoir, conseil',
  'Les phrases du quotidien pour demander, autoriser, interdire et conseiller. Les formes en なきゃ / ないと sont celles qu’on entend à l’oral.',
  [
   ['V-てもいい', 'Permission : « on peut… »', 'ここで写真を撮ってもいいですか。', 'Je peux prendre des photos ici ?'],
   ['V-てはいけない', 'Interdiction', 'ここで泳いではいけません。', 'Il est interdit de nager ici.'],
   ['V-なくてもいい', 'Pas besoin de (absence d’obligation)', '明日は来なくてもいいです。', 'Tu n’as pas besoin de venir demain.'],
   ['V-なければならない', 'Devoir (obligation, assez soutenu)', '薬を飲まなければなりません。', 'Je dois prendre mon médicament.'],
   ['V-ないといけない', 'Devoir (courant à l’oral)', 'もう帰らないといけません。', 'Je dois rentrer maintenant.'],
   ['V-なきゃ / V-なくちゃ', 'Devoir, forme contractée familière', '早く寝なきゃ。', 'Il faut que j’aille dormir tôt.'],
   ['V-たほうがいい', 'Conseil : « tu ferais bien de »', '早く病院に行ったほうがいいですよ。', 'Vous devriez aller vite à l’hôpital.'],
   ['V-ないほうがいい', 'Conseil négatif', '夜遅くコーヒーを飲まないほうがいいです。', 'Mieux vaut ne pas boire de café tard le soir.'],
   ['V-てほしい', 'Vouloir que quelqu’un fasse (personne に + V-てほしい)', '友達に手伝ってほしいです。', 'Je voudrais que mon ami m’aide.'],
   ['V-ないでください', 'Prière de ne pas…', 'ここに荷物を置かないでください。', 'Ne posez pas vos bagages ici.'],
   ['V-てもらえませんか', 'Demande polie : « pourriez-vous… ? »', '写真を撮ってもらえませんか。', 'Pourriez-vous me prendre en photo ?'],
   ['V-させてください', 'Permettez-moi de… (causatif + ください)', '自己紹介をさせてください。', 'Permettez-moi de me présenter.'],
  ],
  'Pour les conseils, たほうがいい prend le passé (行ったほうがいい) mais ないほうがいい prend le présent négatif. Les formes du passif et du causatif sont dans Conjugaison.'),

 sub('理由・目的・対比 — Cause, but, contraste',
  'Pour expliquer pourquoi, dans quel but, ou pour opposer deux faits. La forme simple précède ので, のに et し ; les adjectifs en な et les noms prennent な devant ので et のに.',
  [
   ['～ので', 'Cause objective, ton poli et neutre (adjectif en な / nom : なので)', '雨なので、行きません。', 'Comme il pleut, je n’y vais pas.'],
   ['～し', 'Énumérer des raisons : « et en plus »', '安いし、おいしいし、この店が好きです。', 'C’est pas cher, c’est bon : j’aime ce restaurant.'],
   ['～のに', 'Contraste inattendu : « alors que »', '勉強したのに、試験に落ちました。', 'J’avais étudié, et pourtant j’ai échoué à l’examen.'],
   ['～ても / ～でも', 'Même si', '雨が降っても、行きます。', 'Même s’il pleut, j’y vais.'],
   ['～けど / ～けれども', 'Mais (l’oral adoucit)', '高いけど、買います。', 'C’est cher, mais je l’achète.'],
   ['V-る / Nの + ために', 'But : « afin de » (volonté du sujet)', '日本語を勉強するために、日本に行きます。', 'Je vais au Japon pour étudier le japonais.'],
   ['V-る / V-ない + ように', 'But : « pour que » (état souhaité, verbe de capacité ou sans volonté)', '忘れないように、メモします。', 'Je note pour ne pas oublier.'],
   ['V-ながら', 'Deux actions en même temps (radical en ます)', '音楽を聞きながら、勉強します。', 'J’étudie en écoutant de la musique.'],
   ['V-ないで', 'Sans faire…', '朝ご飯を食べないで、出かけました。', 'Je suis sorti sans prendre de petit-déjeuner.'],
   ['Nでも', 'Même N ; ou « par exemple N » pour proposer', 'お茶でも飲みませんか。', 'Si on prenait un thé, par exemple ?'],
  ],
  'ので est plus doux que から pour expliquer ou s’excuser (遅れたので…). ために exprime le but d’une action voulue ; ように sert quand ce qu’on vise n’est pas une action volontaire (忘れない, 聞こえる, 話せる).'),

 sub('変化・習慣・決定 — Changement, habitude, décision',
  'Pour dire qu’une situation change, qu’on s’y efforce, ou qu’une décision est prise par soi ou par les circonstances.',
  [
   ['～くなる / ～になる', 'Devenir (adjectif en い : く ; adjectif en な / nom : に)', '寒くなりました。', 'Il fait plus froid.'],
   ['V-るようになる', 'Arriver à, se mettre à (nouvelle capacité ou habitude)', '日本語が話せるようになりました。', 'Je suis arrivé à parler japonais.'],
   ['V-るようにする', 'S’efforcer de (effort conscient)', '毎日運動するようにしています。', 'Je m’efforce de faire de l’exercice chaque jour.'],
   ['V-ることにする', 'Décider soi-même de', '来年、日本に行くことにしました。', 'J’ai décidé d’aller au Japon l’an prochain.'],
   ['V-ることになる', 'Il est décidé que… (par les circonstances ou d’autres)', '来月から大阪で働くことになりました。', 'Il a été décidé que je travaille à Osaka à partir du mois prochain.'],
   ['V-ることにしている', 'Avoir pour règle de', '毎朝、走ることにしています。', 'J’ai pour règle de courir chaque matin.'],
   ['V-たことがある', 'Avoir déjà fait (expérience)', '富士山に登ったことがあります。', 'J’ai déjà gravi le mont Fuji.'],
   ['V-ることがある', 'Il arrive que (de temps en temps)', 'たまに電車に乗り遅れることがあります。', 'Il m’arrive parfois de rater mon train.'],
   ['V-たり V-たりする', 'Citer des actions parmi d’autres', '休みの日は、映画を見たり本を読んだりします。', 'Les jours de congé, je regarde des films, je lis, etc.'],
   ['V-るつもりだ', 'Avoir l’intention de', '夏に日本へ行くつもりです。', 'J’ai l’intention d’aller au Japon cet été.'],
   ['V-(よ)うと思う', 'Projet (volitif + と思っている)', '来年、日本語を習おうと思っています。', 'Je pense me mettre au japonais l’an prochain.'],
  ],
  'ことにする = ma décision ; ことになる = cela a été décidé (souvent par l’entreprise, la loi, les circonstances). On l’emploie même quand la décision vient de soi, pour sonner modeste : 結婚することになりました.'),

 sub('推量・様子 — Probabilité, apparence, ouï-dire',
  'Les nuances de « peut-être », « probablement », « on dirait » et « il paraît ». Le détail de そう・よう・らしい est aussi dans Expressions.',
  [
   ['～かもしれない', 'Peut-être (possibilité)', '明日は雨かもしれません。', 'Il pleuvra peut-être demain.'],
   ['～でしょう / ～だろう', 'Probablement ; avec une intonation montante : « n’est-ce pas ? »', '彼はもう帰ったでしょう。', 'Il est probablement déjà rentré.'],
   ['～はずだ', 'Ça devrait être le cas (attente fondée sur des faits)', '彼は今日来るはずです。', 'Il doit venir aujourd’hui (normalement).'],
   ['～そうだ (apparence)', 'A l’air de (radical en ます, adjectif sans い / な)', 'このケーキはおいしそうです。', 'Ce gâteau a l’air délicieux.'],
   ['～そうだ (ouï-dire)', 'Il paraît que (forme simple + そうだ)', '明日は雪が降るそうです。', 'Il paraît qu’il neigera demain.'],
   ['～ようだ / ～みたいだ', 'On dirait que, apparemment (jugement personnel d’après des indices)', '田中さんは疲れているようです。', 'Tanaka a l’air fatigué.'],
   ['～らしい', 'Il paraît que (information indirecte) ; typique de', 'あの店は人気があるらしいです。', 'Il paraît que ce magasin est populaire.'],
  ],
  'Piège : おいしそうだ (« a l’air bon », on le voit) ≠ おいしいそうだ (« il paraît que c’est bon », on l’a entendu). L’adjectif いい devient よさそう, et ない devient なさそう.'),

 sub('名詞化・疑問・引用 — Subordonnées, questions intégrées, citations',
  'Pour insérer une phrase dans une autre : transformer un verbe en nom, rapporter une question ou des paroles, situer dans le temps.',
  [
   ['V-るのが / V-ることが', 'Nominaliser un verbe (の plus oral et concret, こと plus abstrait)', '泳ぐのが好きです。', 'J’aime nager.'],
   ['V-ることができる', 'Pouvoir (capacité, possibilité)', '日本語を話すことができます。', 'Je sais parler japonais.'],
   ['～かどうか', 'Si… ou non', '彼が来るかどうか分かりません。', 'Je ne sais pas s’il viendra ou non.'],
   ['疑問詞 + ～か', 'Question intégrée : qui, quoi, où, quand…', '駅がどこにあるか教えてください。', 'Dites-moi où se trouve la gare.'],
   ['～と思う', 'Je pense que (forme simple + と)', '彼は来ないと思います。', 'Je pense qu’il ne viendra pas.'],
   ['～と言う', 'Dire que (citation indirecte)', '田中さんは明日来ると言いました。', 'Tanaka a dit qu’il viendrait demain.'],
   ['～という + N', 'Appelé, qui s’appelle', '「さくら」という店に行きました。', 'Je suis allé dans un magasin appelé « Sakura ».'],
   ['V-るとき / V-たとき', 'Quand (V-る : avant ou pendant ; V-た : une fois l’action faite)', '日本へ行くとき、パスポートを持って行きます。', 'Quand je vais au Japon, j’emporte mon passeport.'],
   ['V-る前に / V-たあとで / V-てから', 'Avant de / après avoir / une fois que', '食べる前に、手を洗います。', 'Je me lave les mains avant de manger.'],
   ['～間に', 'Pendant que (période, action ponctuelle)', '私が寝ている間に、雨が降りました。', 'Il a plu pendant que je dormais.'],
   ['～んです / ～のです', 'Explication, justification ; demander une explication', 'どうしたんですか。頭が痛いんです。', 'Qu’est-ce qui se passe ? J’ai mal à la tête.'],
  ],
  'Dans une subordonnée, le sujet prend が (et non は) : 私が作った料理. Le temps du verbe avant とき dépend du moment relatif à l’action principale, pas du moment présent.'),

 sub('比較・程度 — Comparer, limiter, quantité',
  'Comparaisons, restrictions et degrés. L’ordre de la phrase est toujours : thème, point de comparaison, adjectif.',
  [
   ['AはBより～', 'A est plus… que B', '電車はバスより速いです。', 'Le train est plus rapide que le bus.'],
   ['AよりBのほうが～', 'B est plus… que A (on met l’accent sur B)', '夏より冬のほうが好きです。', 'Je préfère l’hiver à l’été.'],
   ['AはBほど～ない', 'A n’est pas aussi… que B', '今年は去年ほど寒くないです。', 'Cette année, il ne fait pas aussi froid que l’an dernier.'],
   ['～の中でいちばん', 'Le plus… parmi', '果物の中で、りんごがいちばん好きです。', 'De tous les fruits, c’est la pomme que je préfère.'],
   ['～ぐらい / ～くらい', 'Environ ; à peu près', '駅まで歩いて30分ぐらいかかります。', 'Il faut environ 30 minutes à pied jusqu’à la gare.'],
   ['～しか～ない', 'Ne… que (toujours avec un verbe négatif)', '千円しかありません。', 'Je n’ai que mille yens.'],
   ['～ずつ', 'Chacun, par portions égales', '一人二個ずつ取ってください。', 'Prenez-en deux chacun.'],
   ['V-やすい / V-にくい', 'Facile / difficile à… (radical en ます)', 'この本は読みやすいです。', 'Ce livre est facile à lire.'],
   ['V-てばかりいる', 'Ne faire que… (reproche)', '弟はゲームをしてばかりいます。', 'Mon petit frère ne fait que jouer aux jeux vidéo.'],
  ],
  'しか est suivi d’une négation (千円しかない), alors que だけ est suivi d’une affirmation (千円だけある).'),

 sub('話し言葉 — Contractions de l’oral',
  'À l’oral, beaucoup de formes se raccourcissent. Les connaître aide à comprendre les conversations et les séries ; à l’écrit ou en situation formelle, garde la forme complète.',
  [
   ['V-ている → V-てる', 'Contraction de ている', '何してるの？', 'Qu’est-ce que tu fais ?'],
   ['V-ておく → V-とく', 'Contraction de ておく', 'メモしとくね。', 'Je le note (pour plus tard).'],
   ['V-てしまう → V-ちゃう', 'Contraction de てしまう (で → じゃう)', '全部食べちゃった。', 'J’ai tout mangé (oups).'],
   ['V-なければ → V-なきゃ', 'Contraction de なければならない', 'もう行かなきゃ。', 'Il faut que j’y aille.'],
   ['～という → ～って', 'Citer ou présenter quelqu’un, quelque chose', '田中さんって人を知っていますか。', 'Tu connais quelqu’un qui s’appelle Tanaka ?'],
   ['～のだ → ～んだ', 'Explication, réaction', 'そうなんだ。', 'Ah, c’est comme ça !'],
   ['ら抜き言葉', 'Potentiel sans ら (見られる → 見れる) : très courant, mal vu à l’écrit', '一人で食べれる？', 'Tu peux manger tout seul ?'],
  ]),
]

# ═════════════════════════ N3 ═════════════════════════
N3 = [
 sub('原因・理由 — Cause et conséquence',
  'Au niveau N3, on distingue la cause positive, la cause négative et la cause « officielle ». Le choix de la structure en dit long sur l’attitude du locuteur.',
  [
   ['～せいで / ～せいか', 'À cause de (cause négative, on blâme)', '寝坊したせいで、電車に乗り遅れました。', 'À cause de ma grasse matinée, j’ai raté mon train.'],
   ['～おかげで / ～おかげか', 'Grâce à (cause positive, on remercie)', '先生のおかげで、合格できました。', 'Grâce à mon professeur, j’ai réussi.'],
   ['～ため(に)', 'À cause de (formel, écrit, annonces)', '事故のため、電車が遅れています。', 'À cause d’un accident, les trains sont en retard.'],
   ['～ものだから / ～もので', 'Justification, excuse personnelle', '道が混んでいたもので、遅くなりました。', 'Les routes étaient embouteillées, c’est pourquoi je suis en retard.'],
   ['～によって / ～により', 'Par l’effet de, selon (cause, agent ou variation)', '台風によって、電車が止まりました。', 'À cause du typhon, les trains se sont arrêtés.'],
   ['～わけだ', 'C’est donc que, ce n’est pas étonnant (conclusion logique)', '十年日本にいたのか。日本語が上手なわけだ。', 'Il a passé dix ans au Japon ? Pas étonnant qu’il parle si bien.'],
   ['～のだから', 'Puisque (raison évidente pour tous)', '子どもなのだから、仕方がありません。', 'Puisque c’est un enfant, on n’y peut rien.'],
   ['～ばかりに', 'Pour la seule raison que (regret)', '遅れたばかりに、チャンスを逃しました。', 'Pour avoir été en retard, j’ai raté l’occasion.'],
  ],
  'せいで et おかげで ont la même construction mais l’effet inverse : même un résultat identique change de sens selon qu’on remercie ou qu’on accuse.'),

 sub('条件・逆接 — Hypothèse, concession, contraste',
  'Pour formuler une hypothèse ou nuancer une opposition. Le N3 apporte les nuances « même si », « certes mais » et « malgré ».',
  [
   ['たとえ～ても', 'Même si (renforce ても)', 'たとえ雨が降っても、行きます。', 'Même s’il pleut, j’irai.'],
   ['～場合(は)', 'Dans le cas où', '地震が起きた場合は、すぐ逃げてください。', 'En cas de séisme, fuyez immédiatement.'],
   ['～としても', 'Même en supposant que', '失敗したとしても、また挑戦します。', 'Même si j’échouais, je retenterais.'],
   ['～さえ～ば', 'Il suffit de… pour que…', '時間さえあれば、行きたいです。', 'Si seulement j’avais le temps, j’irais.'],
   ['～ない限り', 'Tant que… ne… pas', '練習しない限り、上手になりません。', 'Tant que tu ne t’entraînes pas, tu ne progresseras pas.'],
   ['～ところが', 'Or, pourtant (le résultat contredit l’attente)', '行ってみた。ところが、店は閉まっていた。', 'J’y suis allé. Mais le magasin était fermé.'],
   ['～くせに', 'Alors que (reproche, ton critique)', '知っているくせに、教えてくれません。', 'Il sait, et pourtant il ne me le dit pas.'],
   ['～にもかかわらず', 'Malgré (formel)', '雨にもかかわらず、大勢の人が集まりました。', 'Malgré la pluie, beaucoup de gens se sont réunis.'],
   ['～ものの', 'Certes… mais', '買ったものの、一度も使っていません。', 'Je l’ai acheté, mais je ne l’ai jamais utilisé.'],
   ['～といっても', 'Même si l’on dit que… (nuance la première impression)', '料理ができるといっても、簡単なものだけです。', 'Je sais cuisiner, mais seulement des choses simples.'],
   ['～ながらも', 'Tout en… (deux faits contradictoires)', '悪いと知りながらも、やってしまった。', 'Tout en sachant que c’était mal, je l’ai fait.'],
  ]),

 sub('推量・判断 — Certitude, doute, impossibilité',
  'Pour dire à quel point on est sûr de quelque chose, de « sûrement » à « impossible ».',
  [
   ['～に違いない', 'C’est sûr que (forte conviction du locuteur)', 'この絵は高いに違いない。', 'Ce tableau doit coûter très cher.'],
   ['～に決まっている', 'C’est évident que', 'そんなこと、嘘に決まっています。', 'C’est évidemment un mensonge.'],
   ['～はずがない', 'Il est impossible que', 'あの人が来るはずがありません。', 'Il est impossible qu’il vienne.'],
   ['～わけがない', 'Il n’y a aucune raison que (négation forte)', 'そんな高い物を買えるわけがない。', 'Je ne peux absolument pas acheter une chose aussi chère.'],
   ['～わけではない', 'Cela ne veut pas dire que (négation partielle)', '嫌いなわけではありません。', 'Ce n’est pas que je n’aime pas.'],
   ['～とは限らない', 'Pas forcément, pas toujours', '高いからといって、いいとは限りません。', 'Ce n’est pas parce que c’est cher que c’est bon.'],
   ['～かねない', 'Risque de (conséquence négative)', 'このままでは事故になりかねません。', 'À ce rythme, cela risque de causer un accident.'],
   ['～恐れがある', 'Il y a un risque que (écrit, informations)', '台風が来る恐れがあります。', 'Il y a un risque de typhon.'],
   ['V-そうにない', 'Ne semble pas pouvoir', '今日は終わりそうにありません。', 'Je ne pense pas arriver à finir aujourd’hui.'],
   ['～っぽい', 'A tendance à, a un côté… (informel)', '彼は忘れっぽいです。', 'Il oublie facilement.'],
   ['Nらしい', 'Typique de, digne de', '春らしい天気ですね。', 'Voilà un temps bien printanier.'],
  ],
  'はずがない et わけがない se ressemblent. はず repose sur une attente logique, わけ sur le fait qu’il n’existe aucune raison. わけではない nuance sans nier tout.'),

 sub('時間・順序 — Moment, simultanéité, succession',
  'Pour situer une action dans le temps par rapport à une autre : profiter d’un moment, enchaîner, répéter.',
  [
   ['～うちに', 'Tant que (profiter d’un état qui va changer)', '若いうちに、いろいろな経験をしたいです。', 'Je veux accumuler les expériences tant que je suis jeune.'],
   ['～最中に', 'En plein milieu de', '会議の最中に、電話が鳴りました。', 'Le téléphone a sonné en pleine réunion.'],
   ['V-たとたん(に)', 'À peine… que (fait inattendu)', '外に出たとたん、雨が降り出しました。', 'À peine sorti, la pluie s’est mise à tomber.'],
   ['V-次第', 'Dès que (action volontaire, radical en ます)', '着き次第、連絡します。', 'Je vous contacte dès mon arrivée.'],
   ['V-て以来', 'Depuis que (état qui continue)', '日本に来て以来、毎日納豆を食べています。', 'Depuis mon arrivée au Japon, je mange du natto tous les jours.'],
   ['V-つつある', 'Être en train de (changement progressif, écrit)', '景気は回復しつつあります。', 'L’économie est en train de se rétablir.'],
   ['V-かけ', 'À moitié fait, inachevé (radical en ます)', '読みかけの本があります。', 'J’ai un livre à moitié lu.'],
   ['V-だす', 'Se mettre soudain à (radical en ます)', '突然、子どもが泣きだしました。', 'Soudain, l’enfant s’est mis à pleurer.'],
   ['～ついでに', 'En profitant de, au passage', '買い物のついでに、郵便局に寄りました。', 'En faisant les courses, je suis passé à la poste.'],
   ['～たびに', 'Chaque fois que', 'この歌を聞くたびに、昔を思い出します。', 'Chaque fois que j’entends cette chanson, je repense au passé.'],
  ],
  'うちに insiste sur « avant que la situation ne change » (若いうちに). 間に décrit simplement une période. たとたん ne s’emploie que pour des faits observés, jamais pour sa propre volonté.'),

 sub('義務・助言・意志 — Devoir moral, absence de choix, souhait',
  'Des nuances plus fines que なければならない : ce qu’il est juste de faire, ce qu’on ne peut pas éviter, ce qu’on souhaite fortement.',
  [
   ['V-るべきだ', 'Il faut, on doit (jugement moral ; する → すべき)', '約束は守るべきです。', 'On doit tenir ses promesses.'],
   ['V-ざるを得ない', 'Ne pas avoir d’autre choix que (する → せざるを得ない)', '雨なので、中止せざるを得ません。', 'Vu la pluie, nous ne pouvons qu’annuler.'],
   ['V-ないわけにはいかない', 'Impossible de ne pas…', '上司の誘いだから、行かないわけにはいきません。', 'C’est une invitation de mon chef, je ne peux pas ne pas y aller.'],
   ['V-ることだ', 'Conseil : le mieux est de', '健康のためには、毎日歩くことです。', 'Pour la santé, le mieux est de marcher tous les jours.'],
   ['V-るものだ', 'Il est naturel de ; souvenir : « on avait l’habitude »', '子どものころは、よく川で遊んだものです。', 'Enfant, je jouais souvent à la rivière.'],
   ['V-ることはない', 'Pas besoin de, inutile de', '心配することはありません。', 'Il n’y a pas lieu de s’inquiéter.'],
   ['V-ていられない', 'Ne pas pouvoir rester à… (urgence, impatience)', 'こんなことをしてはいられない。', 'Je ne peux pas rester là à ne rien faire.'],
   ['V-たいものだ', 'J’aimerais bien (souhait fort)', 'いつか日本に住みたいものです。', 'J’aimerais vraiment vivre au Japon un jour.'],
   ['V-(よ)うとする', 'Essayer de ; être sur le point de', '出かけようとしたとき、電話が鳴りました。', 'Au moment où j’allais sortir, le téléphone a sonné.'],
  ]),

 sub('変化・状態・程度 — Tendance, état, degré',
  'Des suffixes très fréquents pour décrire une tendance, un état qui dure ou un degré. La plupart se collent au radical en ます ou à un nom.',
  [
   ['V-がち', 'Avoir tendance à (souvent négatif)', '冬は病気になりがちです。', 'On tombe facilement malade en hiver.'],
   ['N / V-気味', 'Un peu, légèrement (état désagréable)', '風邪気味なので、早く寝ます。', 'Je suis un peu enrhumé, donc je me couche tôt.'],
   ['Nだらけ', 'Plein de (négatif)', '部屋がほこりだらけです。', 'La pièce est pleine de poussière.'],
   ['V-っぱなし', 'Laisser en l’état, négligemment', 'ドアを開けっぱなしにしないでください。', 'Ne laissez pas la porte ouverte.'],
   ['V-きる', 'Faire jusqu’au bout, entièrement', '全部食べきれませんでした。', 'Je n’ai pas pu tout finir.'],
   ['～ほど', 'Au point de (degré)', '涙が出るほどおかしかった。', 'C’était drôle à en pleurer.'],
   ['～ほど～はない', 'Rien n’est plus… que', '家族ほど大切なものはありません。', 'Rien n’est plus précieux que la famille.'],
   ['V-ば V-るほど', 'Plus… plus…', '練習すればするほど、上手になります。', 'Plus on s’entraîne, plus on devient bon.'],
   ['～につれて', 'Au fur et à mesure que', '年をとるにつれて、体力が落ちます。', 'À mesure qu’on vieillit, la forme baisse.'],
   ['～だけでなく', 'Non seulement… mais aussi', '値段が安いだけでなく、味もいいです。', 'Non seulement c’est bon marché, mais c’est aussi bon.'],
   ['～ばかりか', 'Non seulement… mais encore (renchérit)', '彼は英語ばかりか、フランス語も話せます。', 'Non seulement il parle anglais, mais aussi français.'],
  ]),

 sub('強調・限定・対象 — Insister, limiter, rapporter à',
  'Des particules et locutions pour mettre en relief, restreindre ou dire « à propos de », « pour », « comparé à ».',
  [
   ['～さえ', 'Même (même le plus simple, ne serait-ce que)', 'ひらがなさえ読めません。', 'Je ne sais même pas lire les hiragana.'],
   ['～こそ', 'C’est justement… (mise en relief)', '今年こそ、日本へ行きます。', 'Cette année, c’est sûr, j’y vais.'],
   ['～ばかり', 'Presque rien que…', '彼はお菓子ばかり食べています。', 'Il ne mange que des sucreries.'],
   ['～にすぎない', 'Ne… qu’un simple', 'それは噂にすぎません。', 'Ce n’est qu’une rumeur.'],
   ['～に対して', 'Envers ; par opposition à', 'お客様に対して、失礼です。', 'C’est impoli envers les clients.'],
   ['～について / ～に関して', 'À propos de, concernant', '日本の文化について調べています。', 'Je fais des recherches sur la culture japonaise.'],
   ['～にとって', 'Pour (du point de vue de)', '私にとって、家族は大切です。', 'Pour moi, la famille est importante.'],
   ['～に比べて', 'Comparé à', '去年に比べて、今年は暑いです。', 'Comparé à l’an dernier, il fait plus chaud cette année.'],
   ['～として', 'En tant que', '留学生として、日本に来ました。', 'Je suis venu au Japon en tant qu’étudiant étranger.'],
   ['～をはじめ', 'À commencer par', '東京をはじめ、各地で雪が降りました。', 'Il a neigé un peu partout, à commencer par Tokyo.'],
   ['～を中心に', 'Centré sur, autour de', '京都を中心に、観光地を回ります。', 'Je visite des sites touristiques, surtout autour de Kyoto.'],
   ['～によると', 'Selon (source de l’information)', '天気予報によると、明日は雨です。', 'Selon la météo, il pleuvra demain.'],
  ]),

 sub('受身・使役の応用 — Passif et causatif étendus',
  'Au-delà des formes de base : être forcé, subir un désagrément, demander ou recevoir une permission avec politesse.',
  [
   ['V-させられる', 'Être obligé de (causatif passif)', '子どものころ、ピアノを習わされました。', 'Enfant, on m’a obligé à apprendre le piano.'],
   ['V-られる (passif indirect)', 'Subir un désagrément qui nous affecte', '雨に降られました。', 'J’ai été surpris par la pluie.'],
   ['V-(さ)せていただく', 'Humble : « permettez-moi de… »', '今日は休ませていただきます。', 'Permettez-moi de m’absenter aujourd’hui.'],
   ['V-(さ)せてもらう', 'Recevoir la permission de faire', '先に帰らせてもらいます。', 'Je me permets de partir avant.'],
   ['V-ていただけませんか', 'Demande très polie', 'もう一度説明していただけませんか。', 'Pourriez-vous m’expliquer encore une fois ?'],
   ['V-てもらいたい', 'Je voudrais qu’on fasse pour moi', '説明してもらいたいです。', 'J’aimerais que vous m’expliquiez.'],
   ['V-ことになっている', 'Il est prévu, c’est la règle', '日本では、家に入るとき靴を脱ぐことになっています。', 'Au Japon, il est de règle d’enlever ses chaussures en entrant.'],
  ],
  'Le passif indirect (雨に降られた, 子どもに泣かれた) dit que quelqu’un a été gêné par un fait extérieur. Il n’a pas d’équivalent direct en français, on le traduit par « j’ai eu… » ou « surpris par… ».'),

 sub('伝聞・話題 — Ouï-dire, sujet de discussion, citation',
  'Pour rapporter ce qu’on a entendu, revenir sur un sujet ou expliquer le sens d’un mot.',
  [
   ['～ということだ / ～とのことだ', 'Il paraît que (rapporté)', '社長は来週戻るということです。', 'Il paraît que le président rentre la semaine prochaine.'],
   ['～って', 'Il paraît que (oral)', '明日、雨だって。', 'Il paraît qu’il pleuvra demain.'],
   ['～というのは', 'Ce qu’on appelle… c’est…', '「もったいない」というのは、無駄にしたくない気持ちです。', '« Mottainai », c’est le sentiment de ne pas vouloir gaspiller.'],
   ['～ということは', 'Cela signifie que…', '彼が来ないということは、中止ですか。', 'S’il ne vient pas, cela veut-il dire que c’est annulé ?'],
   ['～といえば / ～というと', 'À propos de, quand on parle de', '日本といえば、やはり富士山ですね。', 'Quand on parle du Japon, on pense forcément au mont Fuji.'],
   ['～をめぐって', 'Autour de (sujet de débat)', '新しい法律をめぐって、議論が続いています。', 'Le débat se poursuit autour de la nouvelle loi.'],
   ['～通りに', 'Conformément à', '説明書の通りに組み立てました。', 'J’ai monté selon le mode d’emploi.'],
  ]),

 sub('話し言葉 — Oral naturel',
  'Des tournures qui font la différence entre un japonais de manuel et un japonais vivant. À réserver aux amis, collègues proches et situations décontractées.',
  [
   ['～っけ', 'Rappel d’un détail oublié : « c’était quoi déjà ? »', '彼の名前、何だったっけ。', 'C’était quoi déjà son nom ?'],
   ['～じゃない？', 'Non ? / ça ne serait pas… ? (confirmation)', 'これ、あなたのじゃない？', 'C’est pas à toi, ça ?'],
   ['～かな / ～かしら', 'Je me demande si (soi-même)', '明日は晴れるかな。', 'Je me demande s’il fera beau demain.'],
   ['～っていう + N', 'Appelé (version orale de という)', '「さくら」っていうお店です。', 'C’est un magasin qui s’appelle « Sakura ».'],
   ['～んだもん / ～もの', 'Parce que… (justification, ton enfantin)', 'だって、知らなかったんだもん。', 'Mais bon, je ne savais pas !'],
   ['～って (thème)', 'Reprendre le sujet : « quant à… »', '田中さんって、優しいよね。', 'Tanaka, il est gentil, hein ?'],
   ['～じゃん', 'Tu vois bien ! (familier)', 'いいじゃん。', 'C’est bien, non ?'],
   ['～なんて', 'Des choses comme… (surprise ou dédain)', '私が一番なんて、信じられません。', 'Que je sois première, je n’arrive pas à le croire.'],
   ['～とか', 'Par exemple, des trucs comme', '映画とか見たいです。', 'Je voudrais voir des films, par exemple.'],
  ]),
]

SECTION_N4 = {
 'id': 'gn4', 'jp': 'N4', 'label': 'Grammaire N4', 'replace': None, 'after': '動詞', 'subs': N4,
 'intro': 'Les structures du niveau N4, rangées par fonction : stade de l’action, permission et obligation, cause et but, changement, probabilité, subordonnées, comparaison et oral. Chaque ligne donne la structure, son emploi, un exemple et sa traduction. Le passif, le causatif et le potentiel sont dans Conjugaison ; あげる・くれる・もらう dans Expressions › 授受.'}
SECTION_N3 = {
 'id': 'gn3', 'jp': 'N3', 'label': 'Grammaire N3', 'replace': None, 'after': '動詞', 'subs': N3,
 'intro': 'Les structures du niveau N3 : nuances de cause, concession, certitude, moment, devoir et degré, plus quelques tournures de l’oral. À aborder une fois le N4 solide ; chaque ligne donne la structure, son emploi, un exemple et sa traduction.'}
