# Exemples d'emploi pour les mots de la rubrique « Outils » (affichés dans la correction du quiz vocabulaire).
# Clé : « sous-rubrique|mot » (ou « sous-rubrique|mot|lecture » quand le même mot a deux emplois).
EX = {
 # ── 位置
 '位置|上': ('机の上に本があります。', 'Il y a un livre sur le bureau.'),
 '位置|下': ('ベッドの下に猫がいます。', 'Il y a un chat sous le lit.'),
 '位置|前': ('駅の前で待っています。', "Je t'attends devant la gare."),
 '位置|後ろ': ('私の後ろに立っている人は誰ですか。', 'Qui est la personne debout derrière moi ?'),
 '位置|右': ('次の角を右に曲がってください。', 'Tournez à droite au prochain coin.'),
 '位置|左': ('銀行は郵便局の左にあります。', 'La banque est à gauche de la poste.'),
 '位置|向かい': ('ホテルの向かいにコンビニがあります。', 'Il y a un konbini en face de l’hôtel.'),
 '位置|隣': ('私の隣に座ってください。', 'Asseyez-vous à côté de moi.'),
 '位置|横': ('ドアの横に傘を置きました。', 'J’ai posé le parapluie à côté de la porte.'),
 '位置|すぐ隣': ('薬局はスーパーのすぐ隣です。', 'La pharmacie est juste à côté du supermarché.'),
 '位置|角': ('その角を曲がると駅が見えます。', 'En tournant à ce coin, vous verrez la gare.'),
 '位置|端': ('道の端を歩いてください。', 'Marchez sur le bord de la route.'),
 '位置|中': ('かばんの中に財布があります。', 'Le portefeuille est dans le sac.'),
 '位置|外': ('外は寒いですから、コートを着てください。', 'Il fait froid dehors, mettez un manteau.'),
 '位置|奥': ('トイレは店の奥にあります。', 'Les toilettes sont au fond du magasin.'),
 '位置|表面': ('テーブルの表面がぬれています。', 'La surface de la table est mouillée.'),
 '位置|間': ('銀行と郵便局の間に花屋があります。', 'Il y a un fleuriste entre la banque et la poste.'),
 '位置|周り': ('家の周りに木がたくさんあります。', 'Il y a beaucoup d’arbres autour de la maison.'),
 '位置|近く': ('この近くにコンビニがありますか。', 'Y a-t-il un konbini près d’ici ?'),
 '位置|遠く': ('遠くに富士山が見えます。', 'On voit le mont Fuji au loin.'),
 '位置|そば': ('駅のそばに安いレストランがあります。', 'Il y a un restaurant pas cher près de la gare.'),
 '位置|辺り': ('この辺りに郵便局はありますか。', 'Y a-t-il une poste dans le coin ?'),
 # ── 疑問詞
 '疑問詞|誰': ('あの人は誰ですか。', 'Qui est cette personne ?'),
 '疑問詞|どなた': ('どなたですか。', 'Qui est-ce, s’il vous plaît ?'),
 '疑問詞|何': ('これは何ですか。', 'Qu’est-ce que c’est ?'),
 '疑問詞|どこ': ('トイレはどこですか。', 'Où sont les toilettes ?'),
 '疑問詞|いつ': ('いつ日本へ行きますか。', 'Quand allez-vous au Japon ?'),
 '疑問詞|どう': ('日本の生活はどうですか。', 'Comment est la vie au Japon ?'),
 '疑問詞|どのように': ('駅へはどのように行きますか。', 'Comment va-t-on à la gare ?'),
 '疑問詞|なぜ・どうして': ('どうして遅れましたか。', 'Pourquoi êtes-vous en retard ?'),
 '疑問詞|どんな': ('どんな音楽が好きですか。', 'Quel genre de musique aimez-vous ?'),
 '疑問詞|幾つ': ('りんごはいくつありますか。', 'Combien y a-t-il de pommes ?'),
 '疑問詞|幾ら': ('これはいくらですか。', 'Combien ça coûte ?'),
 '疑問詞|どのくらい': ('駅までどのくらいかかりますか。', 'Combien de temps faut-il jusqu’à la gare ?'),
 # ── 指示詞
 '指示詞|これ': ('これは私のかばんです。', 'Ceci est mon sac.'),
 '指示詞|それ': ('それは何ですか。', 'Qu’est-ce que c’est (ce que tu tiens) ?'),
 '指示詞|あれ': ('あれは東京タワーです。', 'Cela, là-bas, c’est la tour de Tokyo.'),
 '指示詞|どれ': ('あなたの傘はどれですか。', 'Lequel est votre parapluie ?'),
 '指示詞|この': ('この本はおもしろいです。', 'Ce livre est intéressant.'),
 '指示詞|その': ('その時計はいくらですか。', 'Combien coûte cette montre ?'),
 '指示詞|あの': ('あの人は先生です。', 'Cette personne, là-bas, est professeur.'),
 '指示詞|どの': ('どの電車に乗りますか。', 'Quel train prenez-vous ?'),
 '指示詞|こんな': ('こんなに大きい魚は初めて見ました。', 'C’est la première fois que je vois un poisson aussi grand.'),
 '指示詞|そんな': ('そんなことはありません。', 'Ce n’est pas du tout comme ça.'),
 '指示詞|あんな': ('あんなに高い建物は初めてです。', 'Un bâtiment aussi haut, c’est une première.'),
 '指示詞|どんな': ('どんな映画が好きですか。', 'Quel genre de films aimez-vous ?'),
 '指示詞|ここ': ('ここで写真を撮ってもいいですか。', 'Puis-je prendre une photo ici ?'),
 '指示詞|そこ': ('そこに座ってください。', 'Asseyez-vous là, s’il vous plaît.'),
 '指示詞|あそこ': ('あそこにバス停があります。', 'Il y a un arrêt de bus là-bas.'),
 '指示詞|どこ': ('駅はどこですか。', 'Où est la gare ?'),
 '指示詞|こちら': ('こちらへどうぞ。', 'Par ici, s’il vous plaît.'),
 '指示詞|そちら': ('そちらの天気はどうですか。', 'Quel temps fait-il chez vous ?'),
 '指示詞|あちら': ('トイレはあちらです。', 'Les toilettes sont par là-bas.'),
 '指示詞|どちら': ('どちらがいいですか。', 'Lequel préférez-vous ?'),
 '指示詞|こっち': ('こっちに来て。', 'Viens par ici.'),
 '指示詞|そっち': ('そっちは寒い？', 'Il fait froid de ton côté ?'),
 '指示詞|あっち': ('あっちの店に行こう。', 'Allons dans le magasin là-bas.'),
 '指示詞|どっち': ('どっちがいい？', 'Lequel des deux tu préfères ?'),
 '指示詞|こう': ('こうやって作ります。', 'On le prépare comme ceci.'),
 '指示詞|そう': ('はい、そうです。', 'Oui, c’est ça.'),
 '指示詞|ああ': ('ああ言えばよかった。', 'J’aurais dû le dire comme ça.'),
 '指示詞|どう': ('これはどうやって使いますか。', 'Comment utilise-t-on ceci ?'),
 # ── 副詞
 '副詞|今': ('今、忙しいです。', 'Je suis occupé en ce moment.'),
 '副詞|すぐに': ('すぐに行きます。', 'J’y vais tout de suite.'),
 '副詞|もうすぐ': ('もうすぐ電車が来ます。', 'Le train arrive bientôt.'),
 '副詞|もう': ('もう昼ご飯を食べました。', 'J’ai déjà déjeuné.'),
 '副詞|既に': ('彼はすでに帰りました。', 'Il est déjà rentré.'),
 '副詞|まだ': ('まだ宿題が終わっていません。', 'Je n’ai pas encore fini mes devoirs.'),
 '副詞|前に': ('前に日本へ行ったことがあります。', 'Je suis déjà allé au Japon auparavant.'),
 '副詞|後で': ('後で電話します。', 'Je t’appellerai plus tard.'),
 '副詞|それから': ('朝ご飯を食べて、それから学校へ行きます。', 'Je prends mon petit-déjeuner, puis je vais à l’école.'),
 '副詞|同時に': ('二つのことを同時にするのは難しいです。', 'C’est difficile de faire deux choses en même temps.'),
 '副詞|いつも': ('いつも朝六時に起きます。', 'Je me lève toujours à six heures du matin.'),
 '副詞|よく': ('よく映画を見ます。', 'Je regarde souvent des films.'),
 '副詞|時々': ('時々友達と飲みに行きます。', 'Je sors parfois boire un verre avec des amis.'),
 '副詞|めったに': ('めったに外食しません。', 'Je mange rarement au restaurant.'),
 '副詞|全然': ('全然分かりません。', 'Je ne comprends pas du tout.'),
 '副詞|また': ('また来ます。', 'Je reviendrai.'),
 '副詞|毎回': ('毎回同じ席に座ります。', 'Je m’assois chaque fois à la même place.'),
 '副詞|とても': ('この料理はとてもおいしいです。', 'Ce plat est très bon.'),
 '副詞|本当に': ('本当にありがとうございます。', 'Merci vraiment beaucoup.'),
 '副詞|絶対に': ('絶対に行きます。', 'J’irai sans faute.'),
 '副詞|沢山': ('お土産をたくさん買いました。', 'J’ai acheté beaucoup de souvenirs.'),
 '副詞|もっと': ('もっとゆっくり話してください。', 'Parlez plus lentement, s’il vous plaît.'),
 '副詞|少し': ('少し休みましょう。', 'Reposons-nous un peu.'),
 '副詞|ちょっと': ('ちょっと待ってください。', 'Attendez un instant, s’il vous plaît.'),
 '副詞|殆ど': ('お金がほとんどありません。', 'Je n’ai presque plus d’argent.'),
 '副詞|やっと': ('やっと金曜日になりました。', 'C’est enfin vendredi.'),
 '副詞|十分': ('時間は十分あります。', 'Nous avons largement le temps.'),
 '副詞|あまり': ('このラーメンはあまり辛くありません。', 'Ce ramen n’est pas très épicé.'),
 '副詞|全く': ('全く知りませんでした。', 'Je n’en savais absolument rien.'),
 '副詞|ゆっくり': ('ゆっくり歩きましょう。', 'Marchons tranquillement.'),
 '副詞|速く': ('もっと速く走ってください。', 'Courez plus vite, s’il vous plaît.'),
 '副詞|はっきり': ('はっきり言ってください。', 'Dites-le clairement.'),
 '副詞|一緒に': ('一緒に昼ご飯を食べませんか。', 'Voulez-vous déjeuner avec moi ?'),
 '副詞|一人で': ('一人で旅行します。', 'Je voyage seul.'),
 '副詞|突然': ('突然雨が降ってきました。', 'Il s’est mis à pleuvoir soudainement.'),
 '副詞|そっと': ('赤ちゃんをそっと寝かせました。', 'J’ai couché le bébé tout doucement.'),
 '副詞|もちろん': ('もちろん行きます。', 'Bien sûr que j’y vais.'),
 '副詞|大体': ('だいたい十分で着きます。', 'On arrive en dix minutes environ.'),
 '副詞|特に': ('特に魚が好きです。', 'J’aime tout particulièrement le poisson.'),
 '副詞|先ず': ('まず手を洗ってください。', 'Lavez-vous d’abord les mains.'),
 '副詞|次に': ('次に、お湯を入れます。', 'Ensuite, versez l’eau chaude.'),
 '副詞|最後に': ('最後に、ご飯を入れます。', 'Pour finir, ajoutez le riz.'),
 '副詞|だから': ('雨です。だから、行きません。', 'Il pleut. Donc je n’y vais pas.'),
 '副詞|でも': ('高いです。でも、おいしいです。', 'C’est cher. Mais c’est bon.'),
 '副詞|一方': ('兄は背が高い。一方、弟は小さい。', 'Mon grand frère est grand. Par contre, mon petit frère est petit.'),
 '副詞|必ず': ('明日は必ず来てください。', 'Venez sans faute demain.'),
 '副詞|きっと': ('彼はきっと来ますよ。', 'Il viendra sûrement.'),
 '副詞|多分': ('明日は多分雨です。', 'Demain, il pleuvra sans doute.'),
 '副詞|以外': ('日曜日以外は開いています。', 'C’est ouvert tous les jours sauf le dimanche.'),
 '副詞|別': ('それは別の問題です。', 'C’est un autre problème.'),
 '副詞|いつでも': ('いつでも電話してください。', 'Appelez-moi quand vous voulez.'),
 '副詞|どこでも': ('どこでも行けます。', 'On peut aller n’importe où.'),
 '副詞|何でも': ('何でも食べます。', 'Je mange n’importe quoi.'),
 '副詞|誰でも': ('誰でも参加できます。', 'N’importe qui peut participer.'),
 '副詞|どこにも': ('どこにも行きませんでした。', 'Je ne suis allé nulle part.'),
 '副詞|誰も': ('部屋には誰もいません。', 'Il n’y a personne dans la pièce.'),
 '副詞|何も': ('何も食べていません。', 'Je n’ai rien mangé.'),
 # ── 人称
 '人称|私|わたし': ('私は田中です。', 'Je suis Tanaka.'),
 '人称|私|わたくし': ('わたくしは山田と申します。', 'Je m’appelle Yamada (très formel).'),
 '人称|僕': ('僕は学生です。', 'Je suis étudiant (ton masculin décontracté).'),
 '人称|俺': ('俺も行くよ。', 'Moi aussi, j’y vais (masculin brut).'),
 '人称|あたし': ('あたし、これが好き。', 'Moi, j’aime ça (féminin doux).'),
 '人称|私たち': ('私たちは友達です。', 'Nous sommes amis.'),
 '人称|あなた': ('あなたは学生ですか。', 'Êtes-vous étudiant ?'),
 '人称|君': ('君はどこから来たの？', 'Tu viens d’où ?'),
 '人称|お前': ('お前、何してるんだ？', 'Toi, qu’est-ce que tu fais ? (très familier)'),
 '人称|貴様': ('貴様、誰だ！', 'Toi, qui es-tu ! (agressif, à éviter)'),
 '人称|あなたたち': ('あなたたちはどこへ行きますか。', 'Où allez-vous (vous tous) ?'),
 '人称|彼': ('彼は医者です。', 'Il est médecin.'),
 '人称|彼女': ('彼女は先生です。', 'Elle est professeure.'),
 '人称|彼ら': ('彼らは今日来ません。', 'Ils ne viennent pas aujourd’hui.'),
 '人称|この人': ('この人は私の友達です。', 'Cette personne est mon amie.'),
 '人称|こちらの方': ('こちらの方は山田さんです。', 'Voici M. Yamada (poli).'),
 '人称|さん': ('田中さん、おはようございます。', 'Bonjour, M. Tanaka.'),
 '人称|くん': ('健太くん、こっちに来て。', 'Kenta, viens ici.'),
 '人称|ちゃん': ('さくらちゃんはかわいいですね。', 'Sakura est mignonne, n’est-ce pas ?'),
 '人称|様': ('お客様、いらっしゃいませ。', 'Bienvenue, cher client.'),
 '人称|先生': ('山田先生、おはようございます。', 'Bonjour, professeur Yamada.'),
 '人称|氏': ('山田氏は東京で生まれました。', 'M. Yamada est né à Tokyo (style écrit).'),
}
