import os, sys
# (phrase, réponse, 3 mauvaises, traduction, note, rôle, groupe)
PB = [
 ('私＿＿学生です。', 'は', 'を,の,に', 'Moi, je suis étudiant.', 'は : thème de la phrase (« quant à moi »).', 'Thème', 'wg'),
 ('雨＿＿降っています。', 'が', 'を,に,で', 'Il pleut.', 'が : sujet grammatical, information nouvelle.', 'Sujet', 'wg'),
 ('水＿＿飲みます。', 'を', 'に,で,と', 'Je bois de l’eau.', 'を : objet direct de l’action.', 'Objet direct', 'wo'),
 ('七時＿＿起きます。', 'に', 'を,で,が', 'Je me lève à sept heures.', 'に : moment précis.', 'Moment précis', 'nd'),
 ('日本＿＿行きたいです。', 'へ', 'を,で,と', 'Je veux aller au Japon.', 'へ : direction (に est aussi possible).', 'Direction', 'nd'),
 ('図書館＿＿勉強します。', 'で', 'に,を,が', 'J’étudie à la bibliothèque.', 'で : lieu où se déroule l’action.', 'Lieu de l’action', 'nd'),
 ('友達＿＿映画を見ました。', 'と', 'を,で,が', 'J’ai vu un film avec un ami.', 'と : avec (accompagnement).', 'Accompagnement', 'to'),
 ('これは私＿＿本です。', 'の', 'を,が,に', 'C’est mon livre.', 'の : appartenance, relie deux noms.', 'Appartenance', 'ot'),
 ('東京＿＿大阪まで新幹線で行きます。', 'から', 'を,で,に', 'Je vais de Tokyo à Osaka en shinkansen.', 'から : point de départ.', 'Point de départ', 'lm'),
 ('九時から五時＿＿働きます。', 'まで', 'に,で,を', 'Je travaille de 9 h à 17 h.', 'まで : limite dans le temps ou l’espace.', 'Limite (jusqu’à)', 'lm'),
 ('ペン＿＿書きます。', 'で', 'を,に,と', 'J’écris au stylo.', 'で : moyen, instrument.', 'Moyen / instrument', 'nd'),
 ('私＿＿行きます。', 'も', 'を,に,の', 'Moi aussi, j’y vais.', 'も : aussi (remplace は ou が).', 'Addition (aussi)', 'to'),
 ('友達＿＿プレゼントをあげました。', 'に', 'を,と,で', 'J’ai offert un cadeau à un ami.', 'に : destinataire.', 'Destinataire', 'nd'),
 ('先生＿＿質問しました。', 'に', 'を,と,で', 'J’ai posé une question au professeur.', 'に : personne visée par l’action.', 'Destinataire', 'nd'),
 ('犬＿＿好きです。', 'が', 'を,に,で', 'J’aime les chiens.', '好き, 嫌い, 上手, ほしい… prennent が.', 'Objet d’un état (好き, わかる…)', 'wo'),
 ('時間＿＿ありません。', 'が', 'を,に,で', 'Je n’ai pas le temps.', 'ある / いる : が marque ce qui existe.', 'Sujet', 'wo'),
 ('バス＿＿行きます。', 'で', 'に,を,と', 'J’y vais en bus.', 'で : moyen de transport.', 'Moyen / instrument', 'nd'),
 ('電車＿＿乗ります。', 'に', 'を,で,と', 'Je monte dans le train.', '乗る : に marque le véhicule.', '', 'nd'),
 ('東京＿＿住んでいます。', 'に', 'を,と,が', 'J’habite à Tokyo.', '住む : に marque le lieu de résidence.', 'Lieu d’existence', 'nd'),
 ('一人＿＿行きます。', 'で', 'に,を,と', 'J’y vais seul.', 'で : état, nombre de personnes (ひとりで).', '', 'nd'),
 ('日本＿＿来て、よかったです。', 'に', 'を,で,が', 'Je suis content d’être venu au Japon.', '来る : に marque la destination.', 'Destination', 'nd'),
 ('駅＿＿前で会いましょう。', 'の', 'を,に,と', 'Retrouvons-nous devant la gare.', 'の : relie deux noms (駅の前).', 'Lien entre deux noms', 'ot'),
 ('「ありがとう」＿＿言いました。', 'と', 'を,に,が', 'J’ai dit « merci ».', 'と : citation.', 'Citation', 'ot'),
 ('ここで写真＿＿撮ってもいいですか。', 'を', 'が,に,で', 'Puis-je prendre des photos ici ?', 'を : objet direct de 撮る.', 'Objet direct', 'wo'),
 ('猫は犬＿＿小さいです。', 'より', 'から,まで,で', 'Le chat est plus petit que le chien.', 'より : comparaison (que).', 'Comparaison', 'lm'),
 ('日本＿＿一番高い山は富士山です。', 'で', 'に,を,が', 'La plus haute montagne du Japon est le mont Fuji.', 'で : cadre, étendue (« au Japon »).', '', 'nd'),
 ('お茶＿＿どうですか。', 'でも', 'を,に,が', 'Un thé, par exemple ?', 'でも : proposition, « par exemple ».', '', 'ds'),
 ('行きたい＿＿、時間がありません。', 'が', 'から,ので,と', 'Je veux y aller, mais je n’ai pas le temps.', 'が en milieu de phrase : mais.', 'Opposition (mais)', 'cn'),
 ('疲れた＿＿、休みます。', 'から', 'けど,のに,でも', 'Je suis fatigué, donc je me repose.', 'から : parce que, donc.', 'Cause', 'cn'),
 ('高い＿＿、買います。', 'けど', 'から,ので,と', 'C’est cher, mais je l’achète.', 'けど : mais (familier).', 'Opposition (mais)', 'cn'),
 ('薬を飲んだ＿＿、まだ痛いです。', 'のに', 'から,ので,ために', 'J’ai pris un médicament, et pourtant j’ai encore mal.', 'のに : alors que, pourtant (regret, surprise).', 'Pourtant (surprise, regret)', 'cn'),
 ('一つ＿＿ください。', 'だけ', 'しか,も,でも', 'Un seul, s’il vous plaît.', 'だけ : seulement.', 'Restriction (seulement)', 'ds'),
 ('千円＿＿ありません。', 'しか', 'だけ,も,から', 'Je n’ai que mille yens.', 'しか + négatif : ne… que.', 'Restriction (ne… que)', 'ds'),
 ('今日は暑いです＿＿。（Il fait chaud, hein ? — tu cherches l’accord）', 'ね', 'よ,か,が', 'Il fait chaud, n’est-ce pas ?', 'ね : chercher l’accord de l’autre.', 'Chercher l’accord', 'sf'),
 ('この電車は新宿に行きます＿＿。（Je t’informe — tu ne le savais pas）', 'よ', 'ね,か,を', 'Ce train va à Shinjuku, je t’assure.', 'よ : donner une information, affirmer.', 'Informer (« je te le dis »)', 'sf'),
 ('学生です＿＿。（Question）', 'か', 'ね,よ,を', 'Êtes-vous étudiant ?', 'か : particule de question.', 'Question', 'sf'),
 ('一緒に行きません＿＿。（Invitation）', 'か', 'ね,よ,を', 'Tu ne viendrais pas avec moi ?', '〜ませんか : invitation polie.', 'Invitation (〜ませんか)', 'sf'),
 ('何＿＿食べますか。', 'を', 'が,に,で', 'Que mangez-vous ?', 'を : objet direct (何を).', 'Objet direct', 'wo'),
 ('これ＿＿いくらですか。', 'は', 'を,に,の', 'C’est combien, ceci ?', 'は : thème (これは…).', 'Thème', 'wg'),
 ('私＿＿名前は田中です。', 'の', 'を,に,と', 'Je m’appelle Tanaka.', 'の : possession (私の名前).', 'Appartenance', 'ot'),
 # ── は / が ──
 ('誰＿＿来ましたか。', 'が', 'は,を,に', 'Qui est venu ?', 'Un mot interrogatif sujet (誰, 何, どれ…) prend が, jamais は.', 'Sujet', 'wg'),
 ('何＿＿ありますか。', 'が', 'は,を,に', 'Qu’y a-t-il ?', 'Mot interrogatif sujet → が.', 'Sujet', 'wg'),
 ('今日＿＿天気がいいです。', 'は', 'が,を,に', 'Aujourd’hui, il fait beau.', 'は : thème « aujourd’hui » ; が marque le sujet 天気.', 'Thème', 'wg'),
 ('私＿＿コーヒーが好きです。', 'は', 'を,に,で', 'Moi, j’aime le café.', 'は : thème (moi) ; が : l’objet de l’état 好き.', 'Thème', 'wg'),
 ('財布＿＿ありません。', 'が', 'を,に,で', 'Je n’ai pas de portefeuille.', 'ある / ない : が marque ce qui existe ou manque.', 'Sujet', 'wg'),
 ('あそこに人＿＿います。', 'が', 'を,に,で', 'Il y a quelqu’un là-bas.', 'いる : が marque ce qui existe.', 'Sujet', 'wg'),
 ('この本＿＿私のです。', 'は', 'を,に,と', 'Ce livre est à moi.', 'は : thème (ce livre).', 'Thème', 'wg'),
 ('お腹＿＿すきました。', 'が', 'を,に,で', 'J’ai faim.', 'お腹がすく : が marque l’état.', 'Sujet', 'wg'),
 ('頭＿＿痛いです。', 'が', 'を,に,で', 'J’ai mal à la tête.', 'Partie du corps + が + adjectif : mal à…', 'Sujet', 'wg'),
 ('これ＿＿何ですか。', 'は', 'を,に,で', 'Qu’est-ce que c’est ?', 'は : thème (これは何ですか).', 'Thème', 'wg'),
 # ── に / で / へ ──
 ('公園＿＿猫がいます。', 'に', 'で,を,と', 'Il y a un chat dans le parc.', 'に : lieu d’existence (いる / ある).', 'Lieu d’existence', 'nd'),
 ('公園＿＿遊びます。', 'で', 'に,を,と', 'Je joue dans le parc.', 'で : lieu où se déroule l’action.', 'Lieu de l’action', 'nd'),
 ('家＿＿ご飯を食べます。', 'で', 'に,を,と', 'Je mange à la maison.', 'で : lieu de l’action 食べる.', 'Lieu de l’action', 'nd'),
 ('駅＿＿着きました。', 'に', 'で,を,と', 'Je suis arrivé à la gare.', '着く : に marque le point d’arrivée.', 'Destination', 'nd'),
 ('いすの上＿＿本があります。', 'に', 'で,を,と', 'Il y a un livre sur la chaise.', 'に : lieu d’existence (ある).', 'Lieu d’existence', 'nd'),
 ('会議は三階＿＿あります。', 'で', 'に,を,と', 'La réunion se tient au 3e étage.', 'Un événement (会議, パーティー) → で + あります.', 'Lieu de l’action', 'nd'),
 ('はさみ＿＿紙を切ります。', 'で', 'に,を,と', 'Je coupe le papier avec des ciseaux.', 'で : instrument.', 'Moyen / instrument', 'nd'),
 ('日本語＿＿手紙を書きました。', 'で', 'に,と,が', 'J’ai écrit une lettre en japonais.', 'で : moyen, langue utilisée.', 'Moyen / instrument', 'nd'),
 ('友達＿＿会いました。', 'に', 'を,で,が', 'J’ai rencontré un ami.', '会う : に marque la personne rencontrée.', '', 'nd'),
 ('先生＿＿聞きます。', 'に', 'を,で,が', 'Je demande au professeur.', '聞く (demander) : に marque la personne interrogée.', 'Destinataire', 'nd'),
 ('四月＿＿学校が始まります。', 'に', 'で,を,が', 'L’école commence en avril.', 'に : moment précis (mois, heure, date).', 'Moment précis', 'nd'),
 ('何時＿＿終わりますか。', 'に', 'を,が,と', 'À quelle heure ça finit ?', '何時に : à quelle heure.', 'Moment précis', 'nd'),
 ('何曜日＿＿行きますか。', 'に', 'を,が,と', 'Quel jour y allez-vous ?', '何曜日に : quel jour.', 'Moment précis', 'nd'),
 ('日本＿＿何日いますか。', 'に', 'を,と,へ', 'Combien de jours restez-vous au Japon ?', 'いる : に marque le lieu (へ est impossible avec いる).', 'Lieu d’existence', 'nd'),
 ('病院＿＿働いています。', 'で', 'に,を,と', 'Je travaille dans un hôpital.', '働く : で marque le lieu de l’activité.', 'Lieu de l’action', 'nd'),
 ('ホテル＿＿泊まります。', 'に', 'を,が,と', 'Je loge à l’hôtel.', '泊まる : に marque le lieu de séjour.', 'Lieu d’existence', 'nd'),
 ('ここ＿＿座ってもいいですか。', 'に', 'を,で,が', 'Puis-je m’asseoir ici ?', '座る : に marque l’endroit où l’on s’assoit.', '', 'nd'),
 ('右＿＿曲がってください。', 'に', 'を,で,が', 'Tournez à droite.', '右に / 左に曲がる : direction du virage.', 'Direction', 'nd'),
 ('道＿＿迷いました。', 'に', 'を,で,が', 'Je me suis perdu.', '道に迷う : に fait partie de l’expression.', '', 'nd'),
 ('学校＿＿行きます。', 'へ', 'を,で,と', 'Je vais à l’école.', 'へ : direction (に est aussi possible).', 'Direction', 'nd'),
 ('どこ＿＿行きますか。', 'へ', 'を,で,と', 'Où allez-vous ?', 'どこへ / どこに : destination.', 'Direction', 'nd'),
 ('三時＿＿終わります。', 'に', 'へ,を,で', 'Ça finit à trois heures.', 'Un moment précis → に ; へ marque seulement une direction.', 'Moment précis', 'nd'),
 ('母＿＿料理を習いました。', 'に', 'を,で,が', 'J’ai appris à cuisiner avec ma mère.', '習う : に marque la personne qui enseigne.', '', 'nd'),
 # ── を / が ──
 ('ピアノ＿＿上手です。', 'が', 'を,に,で', 'Il (elle) joue bien du piano.', '上手, 下手 : が.', 'Objet d’un état (好き, わかる…)', 'wo'),
 ('日本語＿＿わかります。', 'が', 'を,に,で', 'Je comprends le japonais.', 'わかる : が.', 'Objet d’un état (好き, わかる…)', 'wo'),
 ('車＿＿ほしいです。', 'が', 'に,で,と', 'Je veux une voiture.', 'ほしい : が.', 'Objet d’un état (好き, わかる…)', 'wo'),
 ('映画＿＿見ます。', 'を', 'が,に,で', 'Je regarde un film.', 'を : objet direct.', 'Objet direct', 'wo'),
 ('歌＿＿歌います。', 'を', 'が,に,で', 'Je chante une chanson.', 'を : objet direct.', 'Objet direct', 'wo'),
 ('毎朝、公園＿＿散歩します。', 'を', 'が,に,と', 'Chaque matin, je me promène dans le parc.', '散歩する, 歩く, 渡る : を marque le lieu parcouru.', 'Lieu parcouru', 'wo'),
 ('橋＿＿渡ります。', 'を', 'が,に,と', 'Je traverse le pont.', '渡る : を marque ce que l’on traverse.', 'Lieu parcouru', 'wo'),
 ('私は猫＿＿嫌いです。', 'が', 'を,に,で', 'Je n’aime pas les chats.', '嫌い : が.', 'Objet d’un état (好き, わかる…)', 'wo'),
 ('料理＿＿できますか。', 'が', 'を,に,で', 'Savez-vous cuisiner ?', 'できる : が.', 'Objet d’un état (好き, わかる…)', 'wo'),
 ('子供＿＿います。', 'が', 'を,に,で', 'J’ai des enfants.', 'いる : が marque ce qui existe, donc ce qu’on possède.', 'Sujet', 'wo'),
 ('これ＿＿ください。', 'を', 'が,に,で', 'Donnez-moi ceci, s’il vous plaît.', 'を : objet direct (これをください).', 'Objet direct', 'wo'),
 ('メニュー＿＿見せてください。', 'を', 'が,に,で', 'Montrez-moi le menu, s’il vous plaît.', 'を : objet direct de 見せる.', 'Objet direct', 'wo'),
 ('電話＿＿かけます。', 'を', 'が,に,で', 'Je passe un appel.', '電話をかける : を.', 'Objet direct', 'wo'),
 ('部屋＿＿掃除しました。', 'を', 'が,に,で', 'J’ai nettoyé la chambre.', 'を : objet direct.', 'Objet direct', 'wo'),
 ('日本語＿＿勉強しています。', 'を', 'が,に,で', 'J’étudie le japonais.', 'を : objet direct de 勉強する.', 'Objet direct', 'wo'),
 ('手＿＿洗います。', 'を', 'が,に,で', 'Je me lave les mains.', 'を : objet direct.', 'Objet direct', 'wo'),
 # ── と / や / も ──
 ('りんご＿＿みかんを買いました。（Exactement ces deux fruits, rien d’autre）', 'と', 'や,に,で', 'J’ai acheté des pommes et des mandarines.', 'と : liste complète (A et B, seulement).', 'Liste complète', 'to'),
 ('りんご＿＿みかんなどを買いました。（Entre autres fruits）', 'や', 'に,で,が', 'J’ai acheté des pommes, des mandarines, etc.', 'や : liste partielle (exemples), souvent avec など.', 'Liste d’exemples', 'to'),
 ('日本に＿＿行きました。（Je suis aussi allé au Japon）', 'も', 'は,を,が', 'Je suis aussi allé au Japon.', 'も s’ajoute à に (にも), に ne disparaît pas.', 'Addition (aussi)', 'to'),
 ('コーヒーも紅茶＿＿飲みません。（Ni café ni thé）', 'も', 'は,を,が', 'Je ne bois ni café ni thé.', 'A も B も + négatif : ni A ni B.', 'Addition (aussi)', 'to'),
 ('友達＿＿旅行しました。', 'と', 'を,に,が', 'J’ai voyagé avec un ami.', 'と : avec.', 'Accompagnement', 'to'),
 ('彼＿＿結婚しました。', 'と', 'を,に,で', 'Je me suis marié avec lui.', 'と : réciprocité (結婚する, 会う, けんかする…).', 'Accompagnement', 'to'),
 ('妻＿＿一緒に行きます。', 'と', 'を,に,で', 'J’y vais avec ma femme.', 'と一緒に : avec.', 'Accompagnement', 'to'),
 ('これ＿＿それ、どちらがいいですか。', 'と', 'を,に,で', 'Celui-ci ou celui-là, lequel est mieux ?', 'A と B : liste de deux éléments.', 'Liste complète', 'to'),
 # ── から / まで / より ──
 ('どこ＿＿来ましたか。', 'から', 'を,で,と', 'D’où venez-vous ?', 'から : point de départ, origine.', 'Point de départ', 'lm'),
 ('フランス＿＿来ました。（Je viens de France）', 'から', 'に,を,で', 'Je viens de France.', 'から : origine.', 'Point de départ', 'lm'),
 ('ここ＿＿何分かかりますか。', 'から', 'を,に,で', 'Combien de minutes depuis ici ?', 'から : point de départ.', 'Point de départ', 'lm'),
 ('朝＿＿晩まで働きます。', 'から', 'を,に,で', 'Je travaille du matin au soir.', 'から … まで : de … à …', 'Point de départ', 'lm'),
 ('七時＿＿待ちます。（J’attends jusqu’à 7 h）', 'まで', 'までに,に,から', 'J’attends jusqu’à 7 h.', 'まで : action continue jusqu’à un moment.', 'Limite (jusqu’à)', 'lm'),
 ('明日＿＿宿題を出してください。（Avant demain — date limite）', 'までに', 'まで,には,から', 'Rendez les devoirs avant demain.', 'までに : date limite d’une action ponctuelle.', 'Date limite', 'lm'),
 ('あなた＿＿私のほうが背が高いです。', 'より', 'から,まで,で', 'Je suis plus grand que toi.', 'AよりBのほうが : B est plus … que A.', 'Comparaison', 'lm'),
 ('犬＿＿猫のほうが好きです。', 'より', 'から,まで,で', 'J’aime mieux les chats que les chiens.', 'より : comparaison (que).', 'Comparaison', 'lm'),
 # ── ので / けど / のに / が ──
 ('時間がない＿＿、急ぎましょう。', 'から', 'が,けど,のに', 'Comme on n’a pas le temps, dépêchons-nous.', 'から : cause, raison.', 'Cause', 'cn'),
 ('雨な＿＿、行きません。', 'ので', 'から,けど,と', 'Comme il pleut, je n’y vais pas.', 'ので : cause plus objective ; nom + な + ので (nom + だから).', 'Cause', 'cn'),
 ('寝た＿＿、まだ眠いです。', 'のに', 'から,ので,ために', 'J’ai dormi, et pourtant j’ai encore sommeil.', 'のに : alors que, pourtant.', 'Pourtant (surprise, regret)', 'cn'),
 ('すみません＿＿、駅はどこですか。', 'が', 'から,を,と', 'Excusez-moi, où est la gare ?', 'が : introduction polie (すみませんが…).', 'Opposition (mais)', 'cn'),
 ('このラーメンは高い＿＿、おいしいです。', 'けど', 'から,ので,と', 'Ce ramen est cher, mais il est bon.', 'けど : mais.', 'Opposition (mais)', 'cn'),
 ('勉強した＿＿、試験に落ちました。', 'のに', 'から,ので,ために', 'J’ai étudié, et pourtant j’ai raté l’examen.', 'のに : alors que (déception).', 'Pourtant (surprise, regret)', 'cn'),
 # ── だけ / しか / ばかり / でも ──
 ('水＿＿飲みました。', 'だけ', 'しか,も,でも', 'J’ai bu seulement de l’eau.', 'だけ + verbe affirmatif : seulement.', 'Restriction (seulement)', 'ds'),
 ('水＿＿飲みませんでした。（Je n’ai bu que de l’eau）', 'しか', 'だけ,も,でも', 'Je n’ai bu que de l’eau.', 'しか exige un verbe négatif.', 'Restriction (ne… que)', 'ds'),
 ('漫画＿＿読んでいます。（Il lit toujours la même chose — reproche）', 'ばかり', 'しか,も,でも', 'Il ne lit que des mangas (tout le temps).', 'ばかり : toujours la même chose, souvent un reproche.', 'Restriction (seulement)', 'ds'),
 ('一度＿＿行ったことがありません。（Jamais, pas une seule fois）', 'も', 'しか,だけ,でも', 'Je n’y suis jamais allé, pas même une fois.', '数 + も + négatif : pas même…', '', 'ds'),
 ('何＿＿いいです。（N’importe quoi, ça va）', 'でも', 'だけ,しか,ばかり', 'Peu importe, n’importe quoi me convient.', 'mot interrogatif + でも : n’importe…', '', 'ds'),
 ('子供＿＿できます。（Même un enfant peut le faire）', 'でも', 'だけ,から,の', 'Même un enfant peut le faire.', 'でも : même (extrême).', '', 'ds'),
 # ── ね / よ / か / な ──
 ('どこに行きます＿＿。（Question）', 'か', 'ね,よ,を', 'Où allez-vous ?', 'か : particule de question.', 'Question', 'sf'),
 ('いい天気だ＿＿。（Tu te parles à toi-même, ton familier masculin）', 'な', 'か,を,に', 'Quel beau temps.', 'な : exclamation, monologue (familier, plutôt masculin).', '', 'sf'),
 ('そこに入る＿＿。（Tu interdis : n’y va pas）', 'な', 'ね,よ,か', 'N’y entre pas !', 'forme du dictionnaire + な : interdiction brutale.', 'Interdiction', 'sf'),
 # ── autres : ながら / たら / ば / の ──
 ('テレビを見＿＿、ご飯を食べます。（En même temps）', 'ながら', 'ので,のに,ために', 'Je mange en regardant la télé.', 'V (base ます) + ながら : en même temps.', 'Simultanéité', 'ot'),
 ('雨が降っ＿＿、行きません。', 'たら', 'ながら,ので,のに', 'S’il pleut, je n’y vais pas.', 'た形 + ら : si, quand (condition).', 'Condition', 'ot'),
 ('安けれ＿＿、買います。', 'ば', 'たら,ので,のに', 'Si c’est bon marché, je l’achète.', '安けれ + ば : forme conditionnelle en ば.', 'Condition', 'ot'),
 ('これは日本＿＿お菓子です。', 'の', 'を,に,で', 'C’est une sucrerie du Japon.', 'の : relie deux noms (日本のお菓子).', 'Lien entre deux noms', 'ot'),
 ('東京＿＿天気はどうですか。', 'の', 'を,に,で', 'Quel temps fait-il à Tokyo ?', 'の : relie deux noms (東京の天気).', 'Lien entre deux noms', 'ot'),
 ('私＿＿父は医者です。', 'の', 'を,に,で', 'Mon père est médecin.', 'の : possession, appartenance.', 'Appartenance', 'ot'),
 ('駅＿＿どこですか。', 'は', 'を,に,と', 'Où est la gare ?', 'は : thème (駅は…).', 'Thème', 'wg'),
 ('傘＿＿持っています。', 'を', 'が,に,で', 'J’ai un parapluie.', '持つ : を marque l’objet tenu.', 'Objet direct', 'wo'),
]

PB += [
 ('お酒を飲む＿＿、車で来ないでください。', 'なら', 'を,に,へ', 'Si tu bois de l’alcool, ne viens pas en voiture.', 'なら : « si c’est le cas / puisque tu dis que… » (condition).', 'Condition (なら)', 'ex'),
 ('もし安い＿＿、買います。', 'なら', 'を,に,へ', 'Si c’est bon marché, j’achète.', 'なら : si… (hypothèse sur ce que dit ou suppose l’interlocuteur).', 'Condition (なら)', 'ex'),
 ('みんなに一つ＿＿あげます。', 'ずつ', 'から,より,まで', 'Je donne un exemplaire à chacun.', 'ずつ : « chacun / à chaque fois » (quantité répartie).', 'Répartition (ずつ)', 'ex'),
 ('毎日十分＿＿歩いています。', 'ずつ', 'から,より,まで', 'Je marche dix minutes chaque jour.', 'ずつ : même quantité à chaque fois.', 'Répartition (ずつ)', 'ex'),
 ('一人二枚＿＿チケットを渡します。', 'ずつ', 'から,より,まで', 'Je donne deux billets par personne.', 'ずつ : par personne / chacun.', 'Répartition (ずつ)', 'ex'),
 ('りんごやバナナ＿＿を買いました。', 'など', 'が,に,へ', 'J’ai acheté des pommes, des bananes, etc.', 'など : « etc., des choses comme… » (liste non exhaustive).', 'Exemples (など)', 'ex'),
 ('東京や大阪＿＿の大都市は人が多いです。', 'など', 'が,を,に', 'Dans les grandes villes comme Tokyo ou Osaka, il y a beaucoup de monde.', 'など + の : « des… comme X et Y ».', 'Exemples (など)', 'ex'),
 ('三時＿＿に着きます。', 'ごろ', 'ずつ,だけ,しか', 'J’arrive vers trois heures.', 'ごろ : approximation pour un moment précis (vers 3 h).', 'Environ (ごろ)', 'ex'),
 ('来月の十日＿＿に行く予定です。', 'ごろ', 'ずつ,から,より', 'Je compte y aller vers le dix du mois prochain.', 'ごろ : « vers » pour une date ou une heure.', 'Environ (ごろ)', 'ex'),
 ('駅まで十分＿＿かかります。', 'ぐらい', 'ずつ,しか,より', 'Il faut environ dix minutes jusqu’à la gare.', 'ぐらい／くらい : environ (durée, quantité).', 'Environ (ぐらい)', 'ex'),
 ('今年＿＿合格したいです。', 'こそ', 'だけ,から,まで', 'C’est cette année que je veux réussir.', 'こそ : met en relief (« justement / c’est bien… que »).', 'Insistance (こそ)', 'ex'),
 ('こんな簡単な漢字＿＿書けません。', 'すら', 'から,より,と', 'Je ne sais même pas écrire un kanji aussi simple.', 'すら／さえ : « même » (cas extrême).', 'Même (すら)', 'ex'),
 ('ひらがな＿＿読めません。', 'さえ', 'ずつ,ごろ,から', 'Il/elle ne sait même pas lire les hiragana.', 'さえ : « même » (exemple extrême), avec une négation.', 'Même (さえ)', 'ex'),
 ('子ども＿＿知っています。', 'だって', 'しか,から,より', 'Même un enfant le sait.', 'だって : « même, aussi » (familier).', 'Même (だって)', 'ex'),
 ('お茶＿＿飲みませんか。', 'でも', 'ずつ,ごろ,しか', 'On prendrait pas un thé ou quelque chose ?', 'でも : « par exemple / quelque chose comme » (proposition douce).', 'Proposition (でも)', 'ex'),
 ('日本の文化＿＿勉強しています。', 'について', 'によって,として,に対して', 'J’étudie la culture japonaise (le sujet « culture »).', 'について : à propos de, au sujet de.', 'Sujet (について)', 'ex'),
 ('国＿＿文化が違います。', 'によって', 'について,として,に対して', 'La culture diffère selon les pays.', 'によって : selon, en fonction de.', 'Selon (によって)', 'ex'),
 ('留学生＿＿日本に来ました。', 'として', 'について,によって,に対して', 'Je suis venu au Japon en tant qu’étudiant étranger.', 'として : en tant que, comme.', 'En tant que (として)', 'ex'),
 ('お客さん＿＿丁寧に話します。', 'に対して', 'によって,として,において', 'Je parle poliment aux clients.', 'に対して : envers, à l’égard de.', 'Envers (に対して)', 'ex'),
 ('この会議室＿＿パーティーが開かれます。', 'において', 'として,について,に対して', 'La fête aura lieu dans cette salle de réunion.', 'において : « dans, à » (lieu ou cadre, style formel).', 'Lieu formel (において)', 'ex'),
 ('彼は肉＿＿食べています。', 'ばかり', 'ずつ,ごろ,から', 'Il ne mange que de la viande.', 'ばかり : « rien que, tout le temps » (souvent négatif).', 'Seulement (ばかり)', 'ex'),
 ('昨日＿＿寒くありません。', 'ほど', 'ずつ,ごろ,しか', 'Il ne fait pas aussi froid qu’hier.', 'ほど + négation : « pas aussi… que ».', 'Degré (ほど)', 'ex'),
 ('金曜日＿＿レポートを出してください。', 'までに', 'まで,ずつ,ごろ', 'Remettez le rapport d’ici vendredi.', 'までに : date limite (fait une fois avant). まで = durée continue.', 'Date limite (までに)', 'ex'),
 ('私＿＿、まだまだです。', 'なんか', 'ずつ,ごろ,ほど', 'Moi, je ne suis pas encore bon du tout.', 'なんか : « des gens comme moi » (modestie ou dédain, familier).', 'Dédain (なんか)', 'ex'),
]

if __name__ == '__main__':
    import collections
    print(len(PB), collections.Counter(x[6] for x in PB))
    for x in PB:
        assert x[1] not in x[2].split(','), x
        assert '＿＿' in x[0], x
        assert len(x) == 7
